[workspace]
members = [
    "crates/dot001-parser",
    "crates/dot001-tracer",
    "crates/dot001-cli",
    "crates/dot001-diff",
    "crates/dot001-editor",
    "crates/dot001-checkpoint",
]
resolver = "2"
