[workspace]
members = [
    "lib",
    "crates/dot001-cli",
    "crates/dot001-diff",
    "crates/dot001-editor",
    "crates/dot001-error",
    "crates/dot001-parser",
    "crates/dot001-tracer",
    "crates/dot001-writer",
    "crates/dot001-checkpoint",
    "crates/dot001-watcher",
]
resolver = "2"

[workspace.package]
edition = "2021" 
rust-version = "1.70"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# shared deps can be declared here if desired
criterion = { version = "0.5.1", features = ["html_reports"] }
