[workspace]
members = [
    "crates/dot001-error",
    "crates/dot001-parser",
    "crates/dot001-tracer",
    "crates/dot001-cli",
    "crates/dot001-diff",
    "crates/dot001-editor",
    "crates/dot001-checkpoint",
    "crates/dot001-writer",
    "lib",
]
resolver = "2"

[workspace.dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[workspace.package]
# Minimum supported Rust version; aligns with edition 2024 features
rust-version = "1.85"
