[package]
name = "bllink-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bllink-tracer = { path = "../bllink-tracer" }
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
serde_json = "1.0"
text_trees = "0.1.2"
