[package]
name = "dot001-editor"
version = "0.1.0"
edition = "2024"
license = "gpl-3.0-or-later"

[dependencies]
dot001-parser = { path = "../dot001-parser" }
dot001-tracer = { path = "../dot001-tracer" }
thiserror = "1.0"
